version: '3.8'

services:
  nginx:
    image: nginx:1.25.3
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - api_gateway
    networks:
      - app_network

  api_gateway:
    build:
      context: ./otus_space_battle/services
      dockerfile: api_gateway/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - RESOURCE_MANAGEMENT_URL=http://resource_management:8000
      - BATTLE_MECHANICS_URL=http://battle_mechanics:8000
      - RANKING_URL=http://ranking:8000
      - ANALYTICS_URL=http://analytics:8000
      - AUTH_SERVICE_URL=http://auth_service:8000
    depends_on:
      - resource_management
      - battle_mechanics
      - ranking
      - analytics
      - auth_service
    networks:
      - app_network

  auth_service:
    build:
      context: ./otus_space_battle/services
      dockerfile: auth_service/Dockerfile
    ports:
      - "8001:8000"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=space_battle
      - JWT_SECRET=your_secret_key
      - JWT_ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    depends_on:
      - db
    networks:
      - app_network

  resource_management:
    build:
      context: ./otus_space_battle/services
      dockerfile: resource_management/Dockerfile
    ports:
      - "8002:8000"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=space_battle
      - AUTH_SERVICE_URL=http://auth_service:8000
    depends_on:
      - db
      - auth_service
    networks:
      - app_network

  battle_mechanics:
    build:
      context: ./otus_space_battle/services
      dockerfile: battle_mechanics/Dockerfile
    ports:
      - "8003:8000"
    environment:
      - RESOURCE_MANAGEMENT_URL=http://resource_management:8000
      - AUTH_SERVICE_URL=http://auth_service:8000
    depends_on:
      - resource_management
      - auth_service
    networks:
      - app_network

  ranking:
    build:
      context: ./otus_space_battle/services
      dockerfile: ranking/Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=space_battle
      - AUTH_SERVICE_URL=http://auth_service:8000
    depends_on:
      - db
      - auth_service
    networks:
      - app_network

  analytics:
    build:
      context: ./otus_space_battle/services
      dockerfile: analytics/Dockerfile
    ports:
      - "8004:8000"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - AUTH_SERVICE_URL=http://auth_service:8000
    depends_on:
      - elasticsearch
      - auth_service
    networks:
      - app_network

  game_session:
    build:
      context: ./otus_space_battle/services
      dockerfile: game_session_service/Dockerfile
    ports:
      - "8005:8000"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=space_battle
      - AUTH_SERVICE_URL=http://auth_service:8000
    depends_on:
      - db
      - auth_service
    networks:
      - app_network

  matchmaking:
    build:
      context: ./otus_space_battle/services
      dockerfile: matchmaking_service/Dockerfile
    ports:
      - "8006:8000"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=space_battle
      - AUTH_SERVICE_URL=http://auth_service:8000
      - GAME_SESSION_URL=http://game_session:8000
    depends_on:
      - db
      - auth_service
      - game_session
    networks:
      - app_network

  fleet_management:
    build:
      context: ./otus_space_battle/services
      dockerfile: fleet_management_service/Dockerfile
    ports:
      - "8007:8000"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=space_battle
      - AUTH_SERVICE_URL=http://auth_service:8000
      - RESOURCE_MANAGEMENT_URL=http://resource_management:8000
    depends_on:
      - db
      - auth_service
      - resource_management
    networks:
      - app_network

  db:
    image: postgres:16.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=space_battle
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  elasticsearch:
    image: elasticsearch:8.12.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - app_network
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  kibana:
    image: kibana:8.12.1
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - app_network

  logstash:
    image: logstash:8.12.1
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    depends_on:
      - elasticsearch
    networks:
      - app_network

  prometheus:
    image: prom/prometheus:v2.50.1
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - app_network

  grafana:
    image: grafana/grafana:10.3.3
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - app_network

  test_service:
    build:
      context: ./otus_space_battle/services/test_service
      dockerfile: Dockerfile
    container_name: test_service
    volumes:
      - ./otus_space_battle/services:/app/services
      - ./common:/app/common
      - ./reports:/app/reports
    networks:
      - app_network
    depends_on:
      - api_gateway
      - auth_service
      - battle_mechanics
      - matchmaking
      - ranking
      - resource_management
      - analytics
      - db
      - elasticsearch
    environment:
      - API_GATEWAY_URL=http://api_gateway:8000
      - AUTH_SERVICE_URL=http://auth_service:8000
      - BATTLE_MECHANICS_URL=http://battle_mechanics:8000
      - MATCHMAKING_URL=http://matchmaking:8000
      - RANKING_URL=http://ranking:8000
      - RESOURCE_MANAGEMENT_URL=http://resource_management:8000
      - ANALYTICS_URL=http://analytics:8000
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
  elasticsearch_data:
  prometheus_data:
  grafana_data: 