version: '3.8'

services:
  database_service:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: main_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d main_db" ]
      interval: 5s
      retries: 5
      timeout: 3s

  database_migrations:
    build: ./services/database_service
    container_name: otus_database_migrations
    depends_on:
      database_service:
        condition: service_healthy
    command: ["python", "init_db.py"]  # Запускаем создание таблиц

  api_gateway:
    build: ./services/api_gateway
    container_name: otus_api_gateway
    restart: always
    depends_on:
      - auth_service
      - matchmaking_service
    ports:
      - "80:80"

  auth_service:
    build: ./services/auth_service
    container_name: otus_auth_service
    restart: always
    depends_on:
      database_migrations:
        condition: service_completed_successfully  # Ждём создания таблиц
    environment:
      DATABASE_URL: postgresql://user:password@database_service/main_db
    ports:
      - "8001:8001"
    volumes:
      - ./common:/app/common

  matchmaking_service:
    build: ./services/matchmaking_service
    container_name: otus_matchmaking_service
    restart: always
    depends_on:
      database_migrations:
        condition: service_completed_successfully
    environment:
      DATABASE_URL: postgresql://user:password@database_service/main_db
    ports:
      - "8002:8002"

volumes:
  pgdata:
